inference_model: ./works/rec___korean_PP-OCRv3_rec___rec_08_02_90_random_k_fold_5_2___default_config___finetune/inference_model/best/inference
inference_model_dir: ./works/rec___korean_PP-OCRv3_rec___rec_08_02_90_random_k_fold_5_2___default_config___finetune/inference_model/best
name: rec___korean_PP-OCRv3_rec___rec_08_02_90_random_k_fold_5_2___default_config___finetune
