inference_model: ./works/det___ml_PP-OCRv3_det___det_80_10_10___default_config___finetune/inference_model/best/inference
inference_model_dir: ./works/det___ml_PP-OCRv3_det___det_80_10_10___default_config___finetune/inference_model/best
name: det___ml_PP-OCRv3_det___det_80_10_10___default_config___finetune
