inference_model: ./works/det___MobileNetV3_large_x0_5___ai_hub_det_08_02_90_random_k_fold_5_4___default_config___finetune/inference_model/best/inference
inference_model_dir: ./works/det___MobileNetV3_large_x0_5___ai_hub_det_08_02_90_random_k_fold_5_4___default_config___finetune/inference_model/best
name: det___MobileNetV3_large_x0_5___ai_hub_det_08_02_90_random_k_fold_5_4___default_config___finetune
