dataset_dir: ./datasets
datasets:
- ai_hub_korean_det
label:
  eval:
  - eval_label.txt
  infer:
  - infer_label.txt
  test:
  - test_label.txt
  train:
  - train_label.txt
seed: 100
split:
  eval_ratio: 10
  test_ratio: 10
  train_ratio: 80
