python /home/code/PaddleOCR/tools/train.py         -c /home/configs/rec/PP-OCRv3/multi_language/korean_PP-OCRv3_rec.yml         -o Global.epoch_num=30             Global.pretrained_model=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_1___default_config___finetune/trained_model/latest             Global.print_batch_step=1             Global.save_epoch_step=1             Global.eval_batch_step=[0,100]             Global.checkpoints=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_1___default_config___finetune/trained_model/latest             Global.save_model_dir=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_1___default_config___finetune/trained_model             Train.dataset.data_dir=/home/datasets             Train.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_1/train_label.txt']             Eval.dataset.data_dir=/home/datasets             Eval.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_1/val_label.txt']

        python /home/code/PaddleOCR/tools/train.py         -c /home/configs/rec/PP-OCRv3/multi_language/korean_PP-OCRv3_rec.yml         -o Global.epoch_num=30             Global.pretrained_model=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_2___default_config___finetune/trained_model/latest             Global.print_batch_step=1             Global.save_epoch_step=1             Global.eval_batch_step=[0,100]             Global.checkpoints=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_2___default_config___finetune/trained_model/latest             Global.save_model_dir=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_2___default_config___finetune/trained_model             Train.dataset.data_dir=/home/datasets             Train.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_2/train_label.txt']             Eval.dataset.data_dir=/home/datasets             Eval.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_2/val_label.txt']

        python /home/code/PaddleOCR/tools/train.py         -c /home/configs/rec/PP-OCRv3/multi_language/korean_PP-OCRv3_rec.yml         -o Global.epoch_num=30             Global.pretrained_model=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_3___default_config___finetune/trained_model/latest             Global.print_batch_step=1             Global.save_epoch_step=1             Global.eval_batch_step=[0,100]             Global.checkpoints=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_3___default_config___finetune/trained_model/latest             Global.save_model_dir=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_3___default_config___finetune/trained_model             Train.dataset.data_dir=/home/datasets             Train.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_3/train_label.txt']             Eval.dataset.data_dir=/home/datasets             Eval.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_3/val_label.txt']

        python /home/code/PaddleOCR/tools/train.py         -c /home/configs/rec/PP-OCRv3/multi_language/korean_PP-OCRv3_rec.yml         -o Global.epoch_num=30             Global.pretrained_model=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_4___default_config___finetune/trained_model/latest             Global.print_batch_step=1             Global.save_epoch_step=1             Global.eval_batch_step=[0,100]             Global.checkpoints=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_4___default_config___finetune/trained_model/latest             Global.save_model_dir=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_4___default_config___finetune/trained_model             Train.dataset.data_dir=/home/datasets             Train.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_4/train_label.txt']             Eval.dataset.data_dir=/home/datasets             Eval.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_4/val_label.txt']

        python /home/code/PaddleOCR/tools/train.py         -c /home/configs/rec/PP-OCRv3/multi_language/korean_PP-OCRv3_rec.yml         -o Global.epoch_num=30             Global.pretrained_model=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_5___default_config___finetune/trained_model/latest             Global.print_batch_step=1             Global.save_epoch_step=1             Global.eval_batch_step=[0,100]             Global.checkpoints=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_5___default_config___finetune/trained_model/latest             Global.save_model_dir=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_5___default_config___finetune/trained_model             Train.dataset.data_dir=/home/datasets             Train.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_5/train_label.txt']             Eval.dataset.data_dir=/home/datasets             Eval.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_5/val_label.txt']

        python /home/code/PaddleOCR/tools/train.py         -c /home/configs/rec/PP-OCRv3/multi_language/korean_PP-OCRv3_rec.yml         -o Global.epoch_num=50             Global.pretrained_model=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_1___default_config___finetune/trained_model/latest             Global.print_batch_step=1             Global.save_epoch_step=1             Global.eval_batch_step=[0,100]             Global.checkpoints=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_1___default_config___finetune/trained_model/latest             Global.save_model_dir=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_1___default_config___finetune/trained_model             Train.dataset.data_dir=/home/datasets             Train.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_1/train_label.txt']             Eval.dataset.data_dir=/home/datasets             Eval.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_1/val_label.txt']

        python /home/code/PaddleOCR/tools/train.py         -c /home/configs/rec/PP-OCRv3/multi_language/korean_PP-OCRv3_rec.yml         -o Global.epoch_num=50             Global.pretrained_model=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_2___default_config___finetune/trained_model/latest             Global.print_batch_step=1             Global.save_epoch_step=1             Global.eval_batch_step=[0,100]             Global.checkpoints=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_2___default_config___finetune/trained_model/latest             Global.save_model_dir=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_2___default_config___finetune/trained_model             Train.dataset.data_dir=/home/datasets             Train.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_2/train_label.txt']             Eval.dataset.data_dir=/home/datasets             Eval.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_2/val_label.txt']

        python /home/code/PaddleOCR/tools/train.py         -c /home/configs/rec/PP-OCRv3/multi_language/korean_PP-OCRv3_rec.yml         -o Global.epoch_num=50             Global.pretrained_model=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_3___default_config___finetune/trained_model/latest             Global.print_batch_step=1             Global.save_epoch_step=1             Global.eval_batch_step=[0,100]             Global.checkpoints=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_3___default_config___finetune/trained_model/latest             Global.save_model_dir=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_3___default_config___finetune/trained_model             Train.dataset.data_dir=/home/datasets             Train.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_3/train_label.txt']             Eval.dataset.data_dir=/home/datasets             Eval.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_3/val_label.txt']

        python /home/code/PaddleOCR/tools/train.py         -c /home/configs/rec/PP-OCRv3/multi_language/korean_PP-OCRv3_rec.yml         -o Global.epoch_num=50             Global.pretrained_model=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_4___default_config___finetune/trained_model/latest             Global.print_batch_step=1             Global.save_epoch_step=1             Global.eval_batch_step=[0,100]             Global.checkpoints=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_4___default_config___finetune/trained_model/latest             Global.save_model_dir=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_4___default_config___finetune/trained_model             Train.dataset.data_dir=/home/datasets             Train.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_4/train_label.txt']             Eval.dataset.data_dir=/home/datasets             Eval.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_4/val_label.txt']

        python /home/code/PaddleOCR/tools/train.py         -c /home/configs/rec/PP-OCRv3/multi_language/korean_PP-OCRv3_rec.yml         -o Global.epoch_num=50             Global.pretrained_model=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_5___default_config___finetune/trained_model/latest             Global.print_batch_step=1             Global.save_epoch_step=1             Global.eval_batch_step=[0,100]             Global.checkpoints=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_5___default_config___finetune/trained_model/latest             Global.save_model_dir=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_5___default_config___finetune/trained_model             Train.dataset.data_dir=/home/datasets             Train.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_5/train_label.txt']             Eval.dataset.data_dir=/home/datasets             Eval.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_5/val_label.txt']

        python /home/code/PaddleOCR/tools/train.py         -c /home/configs/rec/PP-OCRv3/multi_language/korean_PP-OCRv3_rec.yml         -o Global.epoch_num=70             Global.pretrained_model=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_1___default_config___finetune/trained_model/latest             Global.print_batch_step=1             Global.save_epoch_step=1             Global.eval_batch_step=[0,100]             Global.checkpoints=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_1___default_config___finetune/trained_model/latest             Global.save_model_dir=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_1___default_config___finetune/trained_model             Train.dataset.data_dir=/home/datasets             Train.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_1/train_label.txt']             Eval.dataset.data_dir=/home/datasets             Eval.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_1/val_label.txt']

        python /home/code/PaddleOCR/tools/train.py         -c /home/configs/rec/PP-OCRv3/multi_language/korean_PP-OCRv3_rec.yml         -o Global.epoch_num=70             Global.pretrained_model=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_2___default_config___finetune/trained_model/latest             Global.print_batch_step=1             Global.save_epoch_step=1             Global.eval_batch_step=[0,100]             Global.checkpoints=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_2___default_config___finetune/trained_model/latest             Global.save_model_dir=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_2___default_config___finetune/trained_model             Train.dataset.data_dir=/home/datasets             Train.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_2/train_label.txt']             Eval.dataset.data_dir=/home/datasets             Eval.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_2/val_label.txt']

        python /home/code/PaddleOCR/tools/train.py         -c /home/configs/rec/PP-OCRv3/multi_language/korean_PP-OCRv3_rec.yml         -o Global.epoch_num=70             Global.pretrained_model=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_3___default_config___finetune/trained_model/latest             Global.print_batch_step=1             Global.save_epoch_step=1             Global.eval_batch_step=[0,100]             Global.checkpoints=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_3___default_config___finetune/trained_model/latest             Global.save_model_dir=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_3___default_config___finetune/trained_model             Train.dataset.data_dir=/home/datasets             Train.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_3/train_label.txt']             Eval.dataset.data_dir=/home/datasets             Eval.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_3/val_label.txt']

        python /home/code/PaddleOCR/tools/train.py         -c /home/configs/rec/PP-OCRv3/multi_language/korean_PP-OCRv3_rec.yml         -o Global.epoch_num=70             Global.pretrained_model=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_4___default_config___finetune/trained_model/latest             Global.print_batch_step=1             Global.save_epoch_step=1             Global.eval_batch_step=[0,100]             Global.checkpoints=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_4___default_config___finetune/trained_model/latest             Global.save_model_dir=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_4___default_config___finetune/trained_model             Train.dataset.data_dir=/home/datasets             Train.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_4/train_label.txt']             Eval.dataset.data_dir=/home/datasets             Eval.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_4/val_label.txt']

        python /home/code/PaddleOCR/tools/train.py         -c /home/configs/rec/PP-OCRv3/multi_language/korean_PP-OCRv3_rec.yml         -o Global.epoch_num=70             Global.pretrained_model=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_5___default_config___finetune/trained_model/latest             Global.print_batch_step=1             Global.save_epoch_step=1             Global.eval_batch_step=[0,100]             Global.checkpoints=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_5___default_config___finetune/trained_model/latest             Global.save_model_dir=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_5___default_config___finetune/trained_model             Train.dataset.data_dir=/home/datasets             Train.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_5/train_label.txt']             Eval.dataset.data_dir=/home/datasets             Eval.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_5/val_label.txt']

        python /home/code/PaddleOCR/tools/train.py         -c /home/configs/rec/PP-OCRv3/multi_language/korean_PP-OCRv3_rec.yml         -o Global.epoch_num=90             Global.pretrained_model=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_1___default_config___finetune/trained_model/latest             Global.print_batch_step=1             Global.save_epoch_step=1             Global.eval_batch_step=[0,100]             Global.checkpoints=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_1___default_config___finetune/trained_model/latest             Global.save_model_dir=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_1___default_config___finetune/trained_model             Train.dataset.data_dir=/home/datasets             Train.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_1/train_label.txt']             Eval.dataset.data_dir=/home/datasets             Eval.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_1/val_label.txt']

        python /home/code/PaddleOCR/tools/train.py         -c /home/configs/rec/PP-OCRv3/multi_language/korean_PP-OCRv3_rec.yml         -o Global.epoch_num=90             Global.pretrained_model=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_2___default_config___finetune/trained_model/latest             Global.print_batch_step=1             Global.save_epoch_step=1             Global.eval_batch_step=[0,100]             Global.checkpoints=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_2___default_config___finetune/trained_model/latest             Global.save_model_dir=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_2___default_config___finetune/trained_model             Train.dataset.data_dir=/home/datasets             Train.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_2/train_label.txt']             Eval.dataset.data_dir=/home/datasets             Eval.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_2/val_label.txt']

        python /home/code/PaddleOCR/tools/train.py         -c /home/configs/rec/PP-OCRv3/multi_language/korean_PP-OCRv3_rec.yml         -o Global.epoch_num=90             Global.pretrained_model=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_3___default_config___finetune/trained_model/latest             Global.print_batch_step=1             Global.save_epoch_step=1             Global.eval_batch_step=[0,100]             Global.checkpoints=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_3___default_config___finetune/trained_model/latest             Global.save_model_dir=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_3___default_config___finetune/trained_model             Train.dataset.data_dir=/home/datasets             Train.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_3/train_label.txt']             Eval.dataset.data_dir=/home/datasets             Eval.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_3/val_label.txt']

        python /home/code/PaddleOCR/tools/train.py         -c /home/configs/rec/PP-OCRv3/multi_language/korean_PP-OCRv3_rec.yml         -o Global.epoch_num=90             Global.pretrained_model=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_4___default_config___finetune/trained_model/latest             Global.print_batch_step=1             Global.save_epoch_step=1             Global.eval_batch_step=[0,100]             Global.checkpoints=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_4___default_config___finetune/trained_model/latest             Global.save_model_dir=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_4___default_config___finetune/trained_model             Train.dataset.data_dir=/home/datasets             Train.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_4/train_label.txt']             Eval.dataset.data_dir=/home/datasets             Eval.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_4/val_label.txt']

        python /home/code/PaddleOCR/tools/train.py         -c /home/configs/rec/PP-OCRv3/multi_language/korean_PP-OCRv3_rec.yml         -o Global.epoch_num=90             Global.pretrained_model=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_5___default_config___finetune/trained_model/latest             Global.print_batch_step=1             Global.save_epoch_step=1             Global.eval_batch_step=[0,100]             Global.checkpoints=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_5___default_config___finetune/trained_model/latest             Global.save_model_dir=/home/output/rec___korean_PP-OCRv3_rec___rec_08_02_90_k_fold_5_5___default_config___finetune/trained_model             Train.dataset.data_dir=/home/datasets             Train.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_5/train_label.txt']             Eval.dataset.data_dir=/home/datasets             Eval.dataset.label_file_list=['/home/dataset_labels/rec_08_02_90_k_fold_5_5/val_label.txt']

        