SUPPORTED:

dataset_dir: /home/datasets/AIHUB/korean_image

x_ext: jpg
y_ext: json

checklist:
    all: null
    train1/source: 
        all: null
        간판:
            all: true
            가로형간판: true
            돌출간판: false
            세로형간판: false
            실내간판: false
            실내안내판: false
            지주이용간판: false
            창문이용광고물: false
            현수막: false
        책표지: 
            all: false
            기타: true
            종교: true
            총류: true
    val1/source: 
        all: null
        간판:
            all: true
            가로형간판: true
            돌출간판: true
            세로형간판: true
            실내간판: true
            실내안내판: true
            지주이용간판: true
            창문이용광고물: true
            현수막: True
        책표지: 
            all: false
            기타: true
            종교: true
            총류: true
    train2/source: 
        all: null
        간판:
            all: true
            가로형간판/가로형간판1: true
            가로형간판/가로형간판2: true
            가로형간판/가로형간판3: true
            가로형간판/가로형간판4: true
            가로형간판/가로형간판5: true
            돌출간판/돌출간판1: true
            돌출간판/돌출간판2: true 
            세로형간판: true
            실내간판/실내간판1: true
            실내간판/실내간판2: true
            실내안내판/실내안내판1: true
            실내안내판/실내안내판2: true
            지주이용간판: true
            창문이용광고물: true
            현수막: True
        책표지: 
            all: false
            총류: true
            철학: true
            종교: true
            사회과학: true
            자연과학: true
            기술과학: true
            예술: true
            언어: true
            문학: true
            역사: true
            기타: true
    val2/source: 
        all: null
        간판:
            all: true
            가로형간판: true
            돌출간판: true 
            세로형간판: true
            실내간판: true
            실내안내판: true
            지주이용간판: true
            창문이용광고물: true
            현수막: True
        책표지: 
            all: false
            총류: true
            철학: true
            종교: true
            사회과학: true
            자연과학: true
            기술과학: true
            예술: true
            언어: true
            문학: true
            역사: true
            기타: true