SUPPORTED:
  zip_ext:
    - zip

  img_ext:
    - jpg
    - png
  label_ext:
    - json
    - txt
    
root: /home/dataset/aihub
img_ext: jpg
label_ext: json

Task:
  PaddleOCR:
    dataset_root: /home/dataset/aihub/hangul_real_image_dataset